version: "3"
services: 
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: workshop
      POSTGRES_DB: workshop
      POSTGRES_PASSWORD: workshop
    ports:
      - 5001:5432
    volumes:
      -  $GOPATH/src/github.com/osmanzz/workshop-backend/docker/schema:/docker-entrypoint-initdb.d

